# Generated by Django 2.0.4 on 2018-04-25 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=19)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSource',
            fields=[
                ('payment_source_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.TimeField(auto_now=True)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_source', models.ForeignKey(db_column='payment_source_id', on_delete=django.db.models.deletion.CASCADE, to='market.PaymentSource')),
            ],
        ),
        migrations.AddField(
            model_name='debitcard',
            name='payment_source',
            field=models.ForeignKey(db_column='payment_source_id', on_delete=django.db.models.deletion.CASCADE, to='market.PaymentSource'),
        ),
    ]
