# Generated by Django 2.0.4 on 2018-04-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debitcard',
            old_name='payment_source',
            new_name='card_pmnt_src_id',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='payment_source',
            new_name='wallet_pmnt_src_id',
        ),
        migrations.AlterField(
            model_name='debitcard',
            name='card_number',
            field=models.CharField(max_length=19, unique=True),
        ),
    ]
