# Generated by Django 2.0.4 on 2018-05-02 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PmntSrc_HAS_Currency',
            new_name='PaymentSourceHasCurrency',
        ),
        migrations.RenameModel(
            old_name='Trader_TradesUsing_Currency',
            new_name='TraderTradesUsingCurrency',
        ),
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
