# Generated by Django 2.0.4 on 2018-04-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20180424_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsource',
            name='payment_source_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
