# Generated by Django 2.0.4 on 2018-05-03 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20180502_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_currency',
        ),
    ]
