# Generated by Django 2.0.4 on 2018-04-25 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20180425_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcard',
            name='card_pmnt_src_id',
            field=models.ForeignKey(db_column='payment_source_id', on_delete=django.db.models.deletion.CASCADE, to='market.PaymentSource', unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_pmnt_src_id',
            field=models.ForeignKey(db_column='payment_source_id', on_delete=django.db.models.deletion.CASCADE, to='market.PaymentSource', unique=True),
        ),
    ]
