# Generated by Django 2.0.4 on 2018-04-25 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20180425_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('user_type', models.CharField(choices=[('AD', 'Admin'), ('TR', 'Trader')], default='TR', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='paymentsource',
            name='u_id',
            field=models.ForeignKey(db_column='user_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='market.User'),
        ),
    ]
