# Generated by Django 2.0.4 on 2018-04-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20180425_0311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsource',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='paymentsource',
            name='created_on',
            field=models.CharField(max_length=20),
        ),
    ]
