# Generated by Django 2.0.4 on 2018-04-27 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20180425_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('currency_type', models.CharField(choices=[('CR', 'Cryptocurrency'), ('UD', 'Currency')], max_length=2)),
                ('converted_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_to_convert', to='market.Currency')),
            ],
        ),
    ]
