# Generated by Django 2.0.4 on 2018-04-27 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20180427_0259'),
        ('market', '0007_currency'),
    ]

    operations = [
    ]
