# Generated by Django 2.0.4 on 2018-04-28 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_merge_20180427_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmntSrc_HAS_Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.CharField(max_length=100)),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Currency')),
                ('pmnt_src_id', models.ForeignKey(db_column='payment_source_id', on_delete=django.db.models.deletion.CASCADE, to='market.PaymentSource')),
            ],
        ),
    ]
