# Generated by Django 2.0.4 on 2018-05-02 00:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_pmntsrc_has_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader_TradesUsing_Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Currency')),
                ('trader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.User')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('transaction_currency', models.CharField(max_length=100)),
                ('amount', models.PositiveSmallIntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('currency_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_currency_name', to='market.Trader_TradesUsing_Currency')),
                ('trader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_traderID', to='market.Trader_TradesUsing_Currency')),
            ],
        ),
        migrations.RenameField(
            model_name='pmntsrc_has_currency',
            old_name='currency_id',
            new_name='currency_name',
        ),
        migrations.AddField(
            model_name='debitcard',
            name='expiry_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='max_limit',
            field=models.PositiveSmallIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
