# Generated by Django 2.0.4 on 2018-05-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20180501_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcard',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
