# Generated by Django 2.0.4 on 2018-05-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_auto_20180501_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateField(),
        ),
    ]
