# Generated by Django 2.0.4 on 2018-05-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20180501_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
